# Generated by Django 3.2 on 2021-06-03 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('office', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('degree', models.CharField(blank=True, max_length=20, null=True, verbose_name='Степень')),
                ('organization', models.CharField(blank=True, max_length=30, null=True, verbose_name='Организация')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Адрес')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('personal_data', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
