# Generated by Django 3.2.4 on 2021-06-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тема работы')),
                ('file', models.FileField(upload_to='media', verbose_name='Работа')),
                ('participant', models.ManyToManyField(to='core.UserProfile')),
            ],
            options={
                'verbose_name': 'Заявка на участие',
                'verbose_name_plural': 'Заявки на участие',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=40, verbose_name='Название конференции')),
                ('count_participant', models.SmallIntegerField(verbose_name='Количество участников')),
                ('application', models.ManyToManyField(to='core.Application')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
    ]
