# Generated by Django 3.2.4 on 2021-06-11 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='conference',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Описание'),
        ),
    ]
